replicas: 1
revisionHistoryLimit: 15
strategy:
  type: Recreate
service:
  port: 80
ingress:
  host: front-dakurach.2sem.students-projects.ru
  path: /
  pathType: Prefix
containerPort: 80
image: dupreeh/sausage-frontend:latest
imagePullPolicy: Always   
resources:
  requests:
    cpu: "200m"
    memory: "164Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"
nginxConf: nginx.conf
